### ISSUE TITLE
Error while updloading an image

### ISSUE THREAD

**Issue by Ladvace** [railwayapp-templates/strapi#103]
I tried to upload an image but I'm getting an error:

<img width="344" alt="image" src="https://github.com/user-attachments/assets/529ec0b1-2e0c-4089-bf56-c27edbb7266f">

**Comment by Ladvace** [comment]
despite I've added the following Cloudinary keys to railway, I still get the error

```
CLOUDINARY_NAME=
CLOUDINARY_KEY=
CLOUDINARY_SECRET=
```

**Comment by Ladvace** [comment]
ok at the end I fixed regenerating new keys from Cloudinary

**Comment by conor909** [comment]
@Ladvace I see the same error, is this an extra step that is documented somewhere?
