### ISSUE TITLE
How to use content type builder

### ISSUE THREAD

**Issue by rpmcoding** [railwayapp-templates/strapi#14]
Deployment was straightforward on railway.app.

However, I am unsure of how to use the content-type builder at /admin/plugins/content-type-builder/content-types/plugin::users-permissions.user

You get the error: Information:  The autoReload feature is required to use this plugin. Start your server with `strapi develop`

----------

From reading strapi docs you are supposed to do this in your localhost.

However, if I checkout the copied repo from the railway deployment, there are is no my-project to execute "yarn develop" against.

**Comment by brody192** [comment]
please create a help thread in our discord server

**Comment by ZeFifi** [comment]
You can't create content-types in production mode ;)

**Comment by xJkit** [comment]
You should manually setup a pq server, a "strapi" role and database, and a few matched env variables.
