### ISSUE TITLE
Regular crashes whilst running on Railway

### ISSUE THREAD

**Issue by Matthewspear** [railwayapp-templates/strapi#2]
I have two instances of Strapi running on Railway (love the service), both the database + server are on Railway (with production + staging environments). 

But since moving to Railway I've experienced regular repetitive overnight crashes like this:

```
[2022-03-15 12:35:58.174] debug: ⛔️ Server wasn't able to start properly.

[2022-03-15 12:35:58.174] error: select "t0"."id" from "admin_users" as "t0" limit $1 - Connection terminated unexpectedly

Error: select "t0"."id" from "admin_users" as "t0" limit $1 - Connection terminated unexpectedly

at Connection. (/app/node_modules/pg/lib/client.js:132:73)
```

I'm on the developer plan, and it seems like either the connection limit is too low, the machine isn't closing connections or that the machine is under resourced...

The example is an older version that I had posted to the forums, but can dump a fresh full debug log if that'll help.

Really struggling to find a solution for it – any help would be great!!

Matt

**Comment by MichaelFrieze** [comment]
I am getting this too. I really want to run Strapi on Railway, but it just isn't working. 

Maybe this is similar to the issue we are having:
https://github.com/strapi/strapi/issues/8117

I have tried adding these settings to my database connection, but they didn't help:

```js
      acquireConnectionTimeout: 5000,
      pool: {
        min: 0,
        max: 10,
        createTimeoutMillis: 8000,
        acquireTimeoutMillis: 8000,
        idleTimeoutMillis: 8000,
        reapIntervalMillis: 1000,
        createRetryIntervalMillis: 100,
      },
```

**Comment by MichaelFrieze** [comment]
I am getting this too. I really want to run Strapi on Railway, but it just isn't working.

**Comment by johnbeynon** [comment]
What's also interesting, is that we (Render) are also having customers reporting this issue when they deploy Strapi to us and it's manifesting in the same error which leads me to believe it's more Strapi related as opposed to our respective platforms?

**Comment by MichaelFrieze** [comment]
> What's also interesting, is that we (Render) are also having customers reporting this issue when they deploy Strapi to us and it's manifesting in the same error which leads me to believe it's more Strapi related as opposed to our respective platforms?

I notice it doesn't happen when I deploy to Digital Ocean's app platform, and others have said the same thing. 

I tried deploying to Fly.io and I had the same issue.

**Comment by johnbeynon** [comment]
It definitely is odd and it's curious what the similarities are between all of our platforms, probably Kubernetes at a guess

**Comment by MichaelFrieze** [comment]
> 

https://github.com/strapi/strapi/issues/11860

**Comment by philohelp** [comment]
I experience this too on railway. Just refresh once or twice. Kind of learnt to live with it.

**Comment by shestakov-vladyslav** [comment]
I am having the same issue on Railway with Strapi

**Comment by shestakov-vladyslav** [comment]
To my mind, if it were possible to increase RAM manually for example to 2GB (minimum for Strapi), as by default it uses ~1Gb or less if you look into metrics
It seems to me that this issue is connected to RAM

![image](https://user-images.githubusercontent.com/18069756/195937042-74ca7739-c821-49e0-861a-fa8d56d045b2.png)
![image](https://user-images.githubusercontent.com/18069756/195937221-1e2d0260-9981-481f-a695-4bc348ef3421.png)

**Comment by LouisVallaey** [comment]
I added `pool: {
      min: 0,
    },` to database.js file, seems to fix the problem.

**Comment by Brunodev** [comment]
@LouisVallaey where i can change this in railwayapp?
