### ISSUE TITLE
Add HOSTNAME env variable to template

### ISSUE THREAD

**Issue by m-pabon** [railwayapp-templates/strapi#56]
I just tried deploying this template in railway and after a successful deploy the deploy logs told me to navigate to my admin endpoint at my production url to register my admin user. When doing so, the dev tools console reported that strapi was trying to connect to `http://127.0.0.1:1337` which isn't correct.

After investigating the [server.js](https://github.com/railwayapp-templates/strapi/blob/main/config/server.js) found in the template it seems it is expecting an env variable to be created called `HOSTNAME` and it should be set to the value `railway`, otherwise it will default to attempting to connect to `http://127.0.0.1:1337` which just results in an endless loading screen / connection error.

I think as part of this template when you deploy strapi it should also include the HOSTNAME env variable by default have it set to `railway`.  Only after adding this variable to my deployment was I able to finally load the admin register page. Hopefully im not missing something but either adding it in the readme or defaulting it I think would be a good idea.

**Comment by brody192** [comment]
The `HOSTNAME` variable was meant to be a way of dynamically detecting the railway environment with the main end goal being to switch between the public and private versions of the database URL variable, when developing locally Strapi would connect to the public URL and when running on railway Strapi would connect to the database over the [private network](https://docs.railway.app/reference/private-networking) saving you on [egress fees](https://docs.railway.app/reference/pricing#usage-pricing).
This same `HOSTNAME` check was also used to swap between a local `127.0.0.1` address and the public URL.

Unfortunately, this is not a reliable method as you've pointed out, while the `HOSTNAME` variable is available during runtime by default, it is not available during the build phase as I have found.

#57 Uses [Environment configurations](https://docs.strapi.io/dev-docs/configurations/environment#environment-configurations) to let Strapi switch between the public and private database URL and the local and public URL of the server.

**Comment by brody192** [comment]
Fixed in #57 
Sorry for the troubles
