### ISSUE TITLE
PostgreSQL database gets wiped on deploy

### ISSUE THREAD

**Issue by legovader09** [railwayapp-templates/strapi#8]
Hello,

I have an issue with the database upon a redeploy, any collection types, or pages I've added get nuked from the database. I can confirm that they get created by viewing them in the PostgreSQL container. 

I am running strapi via `strapi develop` so that I can add collection types, could this be what causes the issue? If so, how would I launch it in production mode while still adding collection types?

**Comment by appelskrutt34** [comment]
Why is this closed? I have the same problem and don't know how to solve

**Comment by legovader09** [comment]
Agreed, this should be mentioned in the readme at the very least if not planned. Though I'm not sure if this is a fault of the blueprint or of railway

**Comment by Milo123459** [comment]
this issue was closed because we can't do anything about it. just make changes on the production db or something, not much else i can suggset

**Comment by conor909** [comment]
@Milo123459 do you have a link to any more info?  Is there a way around or should this not be used in production?
