### ISSUE TITLE
Admin panel after deploy hit localhost:1337

### ISSUE THREAD

**Issue by Eleveenpl** [railwayapp-templates/strapi#9]
Hi,

After I deploy my new Strapi CMS from your repository, when I try to make new admin user at /admin i've got an error:

![Zrzut ekranu 2022-12-19 o 16 42 16](https://user-images.githubusercontent.com/77360482/208464010-f3d24711-1e44-4603-988f-1d10cf1efb72.png)

**Comment by juicydevka** [comment]
Same

**Comment by HaroonAzhar** [comment]
SAME. Just created a new project on the free tier and deployed a basic Strapi template. After Build  I can't access the admin panel.  same  issue

**Comment by Eleveenpl** [comment]
@juicydevka @HaroonAzhar - I solved this problem by upgrading the strapi version to 4.5.4, after which I uploaded the change to the repo together with yarn.lock
<img width="362" alt="Zrzut ekranu 2022-12-25 o 17 28 26" src="https://user-images.githubusercontent.com/77360482/209475494-7462e5b3-d9bd-408d-a369-7db5c1bbb535.png">

**Comment by hanifrev** [comment]
> @juicydevka @HaroonAzhar - I solved this problem by upgrading the strapi version to 4.5.4, after which I uploaded the change to the repo together with yarn.lock <img alt="Zrzut ekranu 2022-12-25 o 17 28 26" width="362" src="https://user-images.githubusercontent.com/77360482/209475494-7462e5b3-d9bd-408d-a369-7db5c1bbb535.png">

really helpful, it works now, thanks

**Comment by iriekun** [comment]
> @juicydevka @HaroonAzhar - I solved this problem by upgrading the strapi version to 4.5.4, after which I uploaded the change to the repo together with yarn.lock <img alt="Zrzut ekranu 2022-12-25 o 17 28 26" width="362" src="https://user-images.githubusercontent.com/77360482/209475494-7462e5b3-d9bd-408d-a369-7db5c1bbb535.png">

you save our days!
